### ISSUE TITLE
Strange username running rtorrent

### ISSUE THREAD

**Issue by rjalexa** [MarkusLange/r_ru-torrent-install-script#1]
First of all thank you a lot for your good work.

I am using your script to quickly reinstall my Raspbian Rpi seedbox after the old microSD died.

As I have an external disk with my seeding torrents I checked the ownership of your /srv/rtorrent tree and found maybe a typo in the username. It's rtorrent-deamon while usually the spelling would be daemon (the a before the e). Not a showstopper but my first chown attempt was in error since I typed the usual name.

May I also suggest that probably a username <= 8 chars can be handier with some commands such as ps aux/ps -efl ?

As a last feedback. Could you give the script the possibility of setting the user:group under which you would run rtorrent etc? In my case the old box was all running under bob:bob and it would have been easier to get my external disk back online.

Take care and again thanks a lot. (PS the arakasi/rtinst script which I always used does not work anymore for me complaining about not being able to install packages)

**Comment by MarkusLange** [comment]
> First of all thank you a lot for your good work.

Thanks I tried my best
> As I have an external disk with my seeding torrents I checked the ownership of your /srv/rtorrent tree and found maybe a typo in the username. It's rtorrent-deamon while usually the spelling would be daemon (the a before the e). Not a showstopper but my first chown attempt was in error since I typed the usual name.

Yes thats my usually type of typo, this happend constantly, I will correct it
> May I also suggest that probably a username <= 8 chars can be handier with some commands such as ps aux/ps -efl ?`

Good point, I will think about it and a shorter name
> As a last feedback. Could you give the script the possibility of setting the user:group under which you would run rtorrent etc? In my case the old box was all running under bob:bob and it would have been easier to get my external disk back online.

Oh I can do that, I had a long conversation with myself, problem is, the user for `rtorrent` is a systemuser only created for rtorrent no home no login, the group also. If you map this to an existing user it will break the idea of the isolated user. Until version 2.2 rtorrent used a local or new user, but with a seperate (system-) user, I was able to operate the rtorrent folder with higher folder permissions. Now srv/rtorrent runs within 770 not 775 anymore

> PS the arakasi/rtinst script which I always used does not work anymore for me complaining about not being able to install packages

I heard about it, arakasi/rtinst script is a bit outdated, but not the less it gave me some good ideas and inspiration for this one.

> Take care
Thanks I hope so

**Comment by MarkusLange** [comment]
Btw. may I can prevent using an existing user, so the rtorrent can set it to any non-existing system-user...
