### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by GitHub-BumBleBee** [MarkusLange/r_ru-torrent-install-script#3]
It is not updating to version 4.2.10 here.

**Comment by MarkusLange** [comment]
Hi @GitHub-BumBleBee,

it does, the release from version 4.2.10 was on the 9 Jan:
![grafik](https://github.com/MarkusLange/r_ru-torrent-install-script/assets/1971238/63a025a4-1f33-4fdd-af02-c9571103f999)

But there is/was a bug stickz missed the versionumber in this release and Rathorian correct this on the 13 Jan:
![grafik](https://github.com/MarkusLange/r_ru-torrent-install-script/assets/1971238/d74adece-cb64-487d-a52c-624f9283766a)

It's updating but rutorrent still showing 4.2.9

**Comment by GitHub-BumBleBee** [comment]
@MarkusLange I understood. So it will always stay like this. Showing Version 4.2.9! Thanks
