### ISSUE TITLE
rrutorrent-install-script.bash link gets 404 : Not found

### ISSUE THREAD

**Issue by swizzles-github** [MarkusLange/r_ru-torrent-install-script#4]
Link appears to be missing

**Comment by MarkusLange** [comment]
Sorry to hear at what part did you see this, some more information would be nice

**Comment by swizzles-github** [comment]
Sorry, it doesn't download the install script. This link https://raw.githubusercontent.com/MarkusLange/r_ru-torrent-install-script/main/rrutorrent-install-script.bash gives a 404

**Comment by MarkusLange** [comment]
Yeah this file doesn't exist anymore now you have to use https://raw.githubusercontent.com/MarkusLange/r_ru-torrent-install-script/main/rrutorrent-install-deamon-script.bash my question is where did you get the link for this file from?

**Comment by swizzles-github** [comment]
Hi from your get_rru_install.bash in the zip file I downloaded

**Comment by MarkusLange** [comment]
Ah I had this kind of supposition, the get_rru_install.bash is adjusted to the new filename, should work now
